package apresentacao;

import controle.Calculadora;
import java.awt.AWTKeyStroke;
import java.awt.Component;
import java.awt.KeyboardFocusManager;
import java.awt.event.KeyEvent;
import java.util.HashSet;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;

/**
 *
 * @author rocr
 */
public class JFrameCalculadora extends javax.swing.JFrame {

    Double valAplic = 0.0;
    Double txSelic = 0.0;
    Double periodo = 0.0;

    public JFrameCalculadora() {
        initComponents();
        HashSet conj = new HashSet(this.getFocusTraversalKeys(KeyboardFocusManager.FORWARD_TRAVERSAL_KEYS)); 
        conj.add(AWTKeyStroke.getAWTKeyStroke(KeyEvent.VK_ENTER, 0)); 
        this.setFocusTraversalKeys(KeyboardFocusManager.FORWARD_TRAVERSAL_KEYS, conj);
    }

    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JFrameCalculadora jFram = new JFrameCalculadora();
                jFram.setLocationRelativeTo(null);
                jFram.setVisible(true);
            }
        });
    }

    private void calcular() {
        Calculadora calc = new Calculadora();
        valAplic = Double.valueOf(jTFValorAplicado.getText().replace(",", "."));
        txSelic = Double.valueOf(jTFTaxaSelic.getText().replace(",", "."));
        periodo = Double.valueOf(jTFPeriodo.getText());
        Double resultado = calc.calcularRentabilidade(valAplic, txSelic, periodo);

        jTFValorFinal.setValue(resultado);
    }

    private void limparCampos() {
        //limpa os campos     
        for (int i = 0; i < getContentPane().getComponentCount(); i++) {
            //varre todos os componentes     
            Component c = getContentPane().getComponent(i);
            if (c instanceof JFormattedTextField) {
                JFormattedTextField field = (JFormattedTextField) c;
                field.setText("");
            }
        }
    }

    private boolean verificaCamposPreenchidos() {
        if (("").equals(jTFValorAplicado.getText()) || ("").equals(jTFTaxaSelic.getText()) || ("").equals(jTFPeriodo.getText())) {
            JOptionPane.showMessageDialog(this, "É necessário preencher todos os campos!");
            return false;
        }

        return true;
    }

    public boolean isValor(String valor) {
        try {
            Double.parseDouble(valor);
            return true;
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "O campo aceita apenas números!");
            return false;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jBCalcular = new javax.swing.JButton();
        jBLimpar = new javax.swing.JButton();
        jTFValorAplicado = new javax.swing.JFormattedTextField();
        jTFTaxaSelic = new javax.swing.JFormattedTextField();
        jTFPeriodo = new javax.swing.JFormattedTextField();
        jTFValorFinal = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora de Rentabilidade");
        setBackground(new java.awt.Color(6, 216, 243));
        setLocationByPlatform(true);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(31, 31, 28));
        jLabel1.setText("Valor Aplicado (R$):");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(19, 19, 11));
        jLabel2.setText("Taxa Selic (% a.a) :");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(19, 19, 11));
        jLabel4.setText("Valor Final (R$): ");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(19, 19, 11));
        jLabel3.setText("Período (dias úteis):");

        jSeparator1.setForeground(new java.awt.Color(69, 105, 111));

        jBCalcular.setText("Calcular");
        jBCalcular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBCalcularMouseClicked(evt);
            }
        });

        jBLimpar.setText("Limpar");
        jBLimpar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBLimparMouseClicked(evt);
            }
        });

        jTFValorAplicado.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        jTFValorAplicado.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTFValorAplicado.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTFValorAplicadoFocusLost(evt);
            }
        });

        jTFTaxaSelic.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        jTFTaxaSelic.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTFTaxaSelic.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTFTaxaSelicFocusLost(evt);
            }
        });

        jTFPeriodo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jTFPeriodo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTFPeriodo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTFPeriodoFocusLost(evt);
            }
        });

        jTFValorFinal.setEditable(false);
        jTFValorFinal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        jTFValorFinal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTFValorFinal.setFocusable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTFValorAplicado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFTaxaSelic, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFPeriodo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFValorFinal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBLimpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBCalcular))
                    .addComponent(jSeparator1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jTFValorAplicado, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTFTaxaSelic, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTFPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTFValorFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBCalcular)
                    .addComponent(jBLimpar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBCalcularMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBCalcularMouseClicked
        if (verificaCamposPreenchidos()) {
            calcular();
        }
    }//GEN-LAST:event_jBCalcularMouseClicked

    private void jBLimparMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBLimparMouseClicked
        limparCampos();
    }//GEN-LAST:event_jBLimparMouseClicked

    private void jTFValorAplicadoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFValorAplicadoFocusLost
        final String valor = jTFValorAplicado.getText().replace(",", ".");

        if (!("").equals(valor) && !isValor(valor)) {
            jTFValorAplicado.setText("");
            jTFValorAplicado.requestFocus();
        }
    }//GEN-LAST:event_jTFValorAplicadoFocusLost

    private void jTFTaxaSelicFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFTaxaSelicFocusLost
        final String valor = jTFTaxaSelic.getText().replace(",", ".");

        if (!("").equals(valor) && !isValor(valor)) {
            jTFTaxaSelic.setText("");
            jTFTaxaSelic.requestFocus();
        }
    }//GEN-LAST:event_jTFTaxaSelicFocusLost

    private void jTFPeriodoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFPeriodoFocusLost
        final String valor = jTFPeriodo.getText().replace(",", ".");

        if (!("").equals(valor) && !isValor(valor)) {
            jTFPeriodo.setText("");
            jTFPeriodo.requestFocus();
        }
    }//GEN-LAST:event_jTFPeriodoFocusLost

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCalcular;
    private javax.swing.JButton jBLimpar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JFormattedTextField jTFPeriodo;
    private javax.swing.JFormattedTextField jTFTaxaSelic;
    private javax.swing.JFormattedTextField jTFValorAplicado;
    private javax.swing.JFormattedTextField jTFValorFinal;
    // End of variables declaration//GEN-END:variables

}
